import Head from "next/head";
import { AltLayout } from "../components";
import { MessageCard } from "../components/dashboard";
import MultiDataBarChart from "../components/MultiDataBarChart";
import { topCards } from "../constants/dashboard";

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>BPMI | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AltLayout>
        <main className={`text-darkText w-full py-6`}>
          <div className="text-white  flex  flex-col lg:flex-row items-center md:justify-between ">
            {topCards.map((card) => (
              <div
                className="  max-h-[200px] md:w-[380px] w-fit p-6 flex flex-col rounded-3xl shadow-xl"
                key={card.id}
              >
                <h3
                  className={` text-darkText  text-[20px] xl:text-[28px] grow mb-10`}
                >
                  {card.content}
                </h3>
                <h3
                  className={` text-primary font-semibold  text-[28px] xl:text-[35px] `}
                >
                  {card.amount}
                  {"  "}
                  <span>{card.title}</span>
                </h3>
              </div>
            ))}
          </div>
          <div className="flex flex-col xl:flex-row justify-between gap-6 my-4 md:my-10">
            <MultiDataBarChart
              title="Voting Poll"
              colours={["#3E4095", "#ececf4"]}
            />
            <MultiDataBarChart
              title="Mystery shopping"
              colours={["#252659", "#323377"]}
            />
          </div>
          <div className="flex flex-col lg:flex-row gap-4 justify-between  overflow-x-auto ">
            <MessageCard />
            <MessageCard />
          </div>
        </main>
      </AltLayout>
    </>
  );
};

export default Dashboard;
