import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Button, Layout } from "../components";
import styles from "../components/style";

const Login = () => {
  return (
    <>
      <Head>
        <title>BPMI | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={`text-darkText`}>
          <section className=" flex  items-center justify-center pt-[150px]  md:pb-[100px] pb-12 ">
            <div
              className="flex justify-center items-center w-full flex-wrap  h-full g-6 text-darkText 
             py-4

            "
            >
              <div className="lg:flex flex-wrap g-0 min-w-fit xl:w-9/12 shadow-lg  m-4  rounded-lg ">
                <div className="lg:w-6/12 p-4 md:px-0  hidden lg:block">
                  <div className="md:p-12  flex flex-col h-full justify-center  max-w-[500px] xl:max-w-none ">
                    <h2
                      className={`${styles.heading2} text-primary text-center mb-4 md:mb-12`}
                    >
                      Jurist Login
                    </h2>
                    <form>
                      <div className="flex flex-wrap -mx-3 mb-2 md:mb-6">
                        <div className="w-full px-3">
                          <label
                            className="block tracking-widemd: text-lg font-bold mb-2"
                            htmlFor="grid-email"
                          >
                            Email
                          </label>
                          <input
                            className="appearance-none block w-full  border border-primary rounded-lg py-3 px-4 mb-3 leading-tight focus:outline-none bg-white focus:border-gray-500"
                            id="grid-email"
                            type="text"
                            placeholder="xyz@example.com"
                          />
                        </div>
                      </div>
                      <div className="flex flex-wrap -mx-3  md:mb-6">
                        <div className="w-full px-3">
                          <label
                            className="block tracking-wide md:text-lg font-bold mb-2"
                            htmlFor="grid-password"
                          >
                            Password
                          </label>
                          <input
                            className=" appearance-none block w-full  border border-primary rounded-lg py-3 px-4 mb-3 leading-tight focus:outline-none bg-white focus:border-gray-500"
                            id="grid-password"
                            type="password"
                            placeholder="********"
                          />
                        </div>
                      </div>
                      <div className="flex items-center justify-between pb-6">
                        <p className="mb-0 mr-2 text-primary text-xs md:text-xl">
                          Forgot Password?
                        </p>
                        <div className="form-group form-check">
                          <input
                            type="checkbox"
                            className="form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-full bg-white checked:bg-primary  focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                            id="exampleCheck3"
                          />
                          <label
                            className="form-check-label inline-block text-primary text-xs md:text-xl"
                            htmlFor="exampleCheck2"
                          >
                            Remember me
                          </label>
                        </div>
                      </div>
                      <div className="flex  justify-center md:mt-4">
                        <Link href="dashboard" passHref={true}>
                          <Button
                            text="Login"
                            styles={
                              "bg-primary text-white px-12 md:px-24 text-sm md:text-xl"
                            }
                          />{" "}
                        </Link>
                      </div>
                    </form>
                  </div>
                </div>
                <div className=" p-6 md:px-0  flex justify-center lg:hidden">
                  <div className="md:p-12  flex flex-col h-full justify-center  max-w-[500px] xl:max-w-none ">
                    <h2
                      className={`${styles.heading2} text-primary text-center mb-4 md:mb-12`}
                    >
                      Jurist Login
                    </h2>
                    <form>
                      <div className="flex flex-wrap -mx-3 mb-2 md:mb-6">
                        <div className="w-full px-3">
                          <label
                            className="block tracking-widemd: text-lg font-bold mb-2"
                            htmlFor="grid-email"
                          >
                            Email
                          </label>
                          <input
                            className="appearance-none block w-full  border border-primary rounded-lg py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                            id="grid-email"
                            type="text"
                            placeholder="xyz@example.com"
                          />
                        </div>
                      </div>
                      <div className="flex flex-wrap -mx-3  md:mb-6">
                        <div className="w-full px-3">
                          <label
                            className="block tracking-wide md:text-lg font-bold mb-2"
                            htmlFor="grid-password"
                          >
                            Password
                          </label>
                          <input
                            className="appearance-none block w-full  border border-primary rounded-lg py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                            id="grid-password"
                            type="password"
                            placeholder="********"
                          />
                        </div>
                      </div>
                      <div className="flex items-center justify-between pb-6">
                        <p className="mb-0 mr-2 text-primary text-xs md:text-xl">
                          Forgot Password?
                        </p>
                        <div className="form-group form-check">
                          <input
                            type="checkbox"
                            className="form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-full bg-white checked:bg-primary  focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                            id="exampleCheck3"
                          />
                          <label
                            className="form-check-label inline-block text-primary text-xs md:text-xl"
                            htmlFor="exampleCheck2"
                          >
                            Remember me
                          </label>
                        </div>
                      </div>
                      <div className="flex  justify-center md:mt-4">
                        <Link href="dashboard" passHref={true}>
                          <Button
                            text="Login"
                            styles={
                              "bg-primary text-white px-12 md:px-24 text-sm md:text-xl"
                            }
                          />{" "}
                        </Link>
                      </div>
                    </form>
                  </div>
                </div>

                <div className="lg:w-6/12 lg:rounded-r-lg rounded-b-lg lg:rounded-bl-none hidden lg:block ">
                  <Image
                    src={`/meeting.jpg`}
                    alt="meeting"
                    width={900}
                    height={900}
                    className="rounded-r-lg h-full"
                  />
                </div>
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
};

export default Login;
