import { useState } from "react";
import Head from "next/head";
import { Herofn, Layout, VoteGuide, Modal } from "../components";
import styles from "../components/style";
import { Questionnairefn } from "../components/votePoll";

import Choice from "../components/votePoll/Choice";

const VotingPoll = () => {
  const [leave, setLeave] = useState(true);
  const [showModal, setModal] = useState(false);

  return (
    <>
      <Head>
        <title>BPMI | Mystery Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={`text-darkText`}>
          <Herofn>
            <div
              className="
        pt-20
      min-h-[490px] lg:h-[520px]
      text-white  flex  items-center justify-end  z-20 px-4"
            >
              <h1 className="lg:text-5xl text-3xl mb-2 leading-[40px] sm:leading-[60px] text-center sm:text-start">
                Mystery Shopping
              </h1>
            </div>
          </Herofn>
          {/* <VoteGuide /> */}
          <section
            className={`${styles.flexCenter} ${styles.paddingX}  flex-col my-20  pt-6 `}
          >
            <h2 className={`${styles.heading2} text-primary text-center`}>
              Rating
            </h2>
            <form className="w-full  flex flex-col ">
              <Questionnairefn modal={() => setModal(true)} />
            </form>
          </section>
          <Modal
            isvisible={showModal}
            onClose={() => setModal(false)}
            context={"Your voting has been completed"}
          />
        </main>
      </Layout>
    </>
  );
};

export default VotingPoll;
